apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-deployment
  template:
    metadata:
      labels:
        app: k8s-deployment
    spec:
      containers:
      - name: k8s-deployment
        image: programarc/k8s:26
        ports:
        - containerPort: 3000
        resources: {}
